services:
  app:
    build:
      context: https://github.com/AMS003010/Copper.git
      dockerfile: api-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://copper:copper@db:5432/copper
      - REDIS_URL=redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318
    depends_on:
      - db
      - redis
      - jaeger
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: copper
      POSTGRES_PASSWORD: copper
      POSTGRES_DB: copper
    ports:
      - "5432:5432"
    volumes:
      - copper_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-alert-rules.yml:/etc/prometheus/prometheus-alert-rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - SPAN_STORAGE_TYPE=memory

volumes:
  copper_data:
  grafana_data:
