services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: copper
      POSTGRES_PASSWORD: copper
      POSTGRES_DB: copper
    ports:
      - "5432:5432"
    volumes:
      - copper_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  copper_data: