services:
  app:
    build:
      context: https://github.com/AMS003010/Copper.git
      dockerfile: api-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://copper:copper@db:5432/copper
    depends_on:
      - db
      - prometheus

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: copper
      POSTGRES_PASSWORD: copper
      POSTGRES_DB: copper
    ports:
      - "5432:5432"
    volumes:
      - copper_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  copper_data:
  grafana_data:

